# Generated by Django 5.2.1 on 2025-06-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finance',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
