# Generated by Django 5.2.1 on 2025-06-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='product_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
