# Generated by Django 5.2.1 on 2025-06-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0003_shippinginfo_checkoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
